### ISSUE TITLE
Akto Burp plugin error

### ISSUE THREAD

**Issue by resource-not-found-blank** [akto-api-security/akto#858]
Error during plugin installation process:
```
java.lang.IllegalArgumentException: Invalid URL
	at burp.Zzt.includeInScope(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at burp.Zkok.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy150.includeInScope(Unknown Source)
	at burp.Zntk.lambda$includeInScope$5(Unknown Source)
	at burp.Zrwr.ZS(Unknown Source)
	at burp.Zntk.includeInScope(Unknown Source)
	at burp.Zfuh.includeInScope(Unknown Source)
	at burp.Znao.includeInScope(Unknown Source)
	at burp.Zex.includeInScope(Unknown Source)
	at com.coreyd97.BurpExtenderUtilities.Preferences.setupProjectSettingsStore(Preferences.java:85)
	at com.coreyd97.BurpExtenderUtilities.Preferences.<init>(Preferences.java:54)
	at com.coreyd97.BurpExtenderUtilities.Preferences.<init>(Preferences.java:39)
	at com.coreyd97.BurpExtenderUtilities.PreferenceFactory.<init>(PreferenceFactory.java:15)
	at com.nccgroup.loggerplusplus.preferences.LoggerPreferenceFactory.<init>(LoggerPreferenceFactory.java:33)
	at com.nccgroup.loggerplusplus.preferences.PreferencesController.<init>(PreferencesController.java:22)
	at com.nccgroup.loggerplusplus.LoggerPlusPlus.registerExtenderCallbacks(LoggerPlusPlus.java:100)
	at burp.Zlfd.Z_(Unknown Source)
	at burp.Ziil.Zx(Unknown Source)
	at burp.Ziiu.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
java.lang.IllegalArgumentException: Invalid URL
	at burp.Zmt9.ZA(Unknown Source)
	at burp.Zrwr.ZS(Unknown Source)
	at burp.Zntk.includeInScope(Unknown Source)
	at burp.Zfuh.includeInScope(Unknown Source)
	at burp.Znao.includeInScope(Unknown Source)
	at burp.Zex.includeInScope(Unknown Source)
	at com.coreyd97.BurpExtenderUtilities.Preferences.setupProjectSettingsStore(Preferences.java:85)
	at com.coreyd97.BurpExtenderUtilities.Preferences.<init>(Preferences.java:54)
	at com.coreyd97.BurpExtenderUtilities.Preferences.<init>(Preferences.java:39)
	at com.coreyd97.BurpExtenderUtilities.PreferenceFactory.<init>(PreferenceFactory.java:15)
	at com.nccgroup.loggerplusplus.preferences.LoggerPreferenceFactory.<init>(LoggerPreferenceFactory.java:33)
	at com.nccgroup.loggerplusplus.preferences.PreferencesController.<init>(PreferencesController.java:22)
	at com.nccgroup.loggerplusplus.LoggerPlusPlus.registerExtenderCallbacks(LoggerPlusPlus.java:100)
	at burp.Zlfd.Z_(Unknown Source)
	at burp.Ziil.Zx(Unknown Source)
	at burp.Ziiu.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
java.lang.IllegalArgumentException: Invalid URL
	at burp.Zmt9.ZA(Unknown Source)
	at burp.Zrwr.ZS(Unknown Source)
	at burp.Zntk.includeInScope(Unknown Source)
	at burp.Zfuh.includeInScope(Unknown Source)
	at burp.Znao.includeInScope(Unknown Source)
	at burp.Zex.includeInScope(Unknown Source)
	at com.coreyd97.BurpExtenderUtilities.Preferences.setupProjectSettingsStore(Preferences.java:85)
	at com.coreyd97.BurpExtenderUtilities.Preferences.<init>(Preferences.java:54)
	at com.coreyd97.BurpExtenderUtilities.Preferences.<init>(Preferences.java:39)
	at com.coreyd97.BurpExtenderUtilities.PreferenceFactory.<init>(PreferenceFactory.java:15)
	at com.nccgroup.loggerplusplus.preferences.LoggerPreferenceFactory.<init>(LoggerPreferenceFactory.java:33)
	at com.nccgroup.loggerplusplus.preferences.PreferencesController.<init>(PreferencesController.java:22)
	at com.nccgroup.loggerplusplus.LoggerPlusPlus.registerExtenderCallbacks(LoggerPlusPlus.java:100)
	at burp.Zlfd.Z_(Unknown Source)
	at burp.Ziil.Zx(Unknown Source)
	at burp.Ziiu.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

```
Burp Professional - 2023.12.1.3

**Comment by eXerc1st** [comment]
I'm also facing this issue

**Comment by Elizarfish** [comment]
Yeah, it affected me too.

**Comment by E1tex** [comment]
Same issue.

**Comment by Gurban77** [comment]
Also same for me and others how we can see. From Burp's user forum: https://forum.portswigger.net/thread/montoyaapi-v2023-12-1-invalid-url-exception-in-includeinscope-api-22aee5ae

**Comment by ankush-jain-akto** [comment]
Hi folks. 

It is indeed because Burp changed their APIs completely. We are still in the process of making Akto extension work with the new APIs - expect it by end of this month. 

Having said that, it will work with the older versions of Burp. Any version pre-2024 should work.

**Comment by ankush-jain-akto** [comment]
[Update 1]

It seems Burp has fixed this issue in a beta vesrion - A new version - 2024.1.1.1-26891 (Early adopter) works.

**Comment by avneesh-akto** [comment]
[Update 2]

Burp has acknowledged the [issue](https://forum.portswigger.net/thread/montoyaapi-v2023-12-1-invalid-url-exception-in-includeinscope-api-22aee5ae) and have released a fix in their `early-adopter` release channel.

Akto Burp plugin will work pre [v2023.10.1](https://portswigger.net/burp/releases/professional-community-2023-10-1) or post [v2024.1.1.1](https://portswigger.net/burp/releases/professional-community-2024-1-1-1)
